title: "Hartanto Ario Widjaya"
description: "Student and Aspiring Mainframer"

url: "https://hartan.to"

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Hartanto Ario Widjaya"
resume_title:                   "Student and Aspiring Mainframer"
resume_contact_email:           "96==@o92CE2?]E@"
resume_header_intro: "<p>I'm a student from Singapore who is looking to explore career options in mainframe. Why? Because they are fun to explore with. Currently looking for opportunities in Singapore or Indonesia.</p>"

resume_looking_for_work:        "yes"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_credentials:     true
resume_section_interests:       true
resume_section_language:        true

resume_social_links:
  resume_github_url:            "https://github.com/tanto259"
  resume_twitter_url:           "https://twitter.com/tanto259"
  resume_linkedin_url:          "https://www.linkedin.com/in/hartantoariowidjaya"
  resume_website_url:           "https://securitypuppy.com"
  resume_facebook_url:          "https://www.facebook.com/tanto259"
  resume_instagram_url:         "https://www.instagram.com/tanto259"
resume_print_social_links:      true

resume_theme:                   default

webmaster_verifications:
  google: 8cZJ7K74aI81G83l-AG_7MegZmsRWMNe7rXrVlvrqo8
  yandex: e19915b37a81f438
  bing: 0C8DA626DE53E04C6AF918B5FB85176E

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .well-known