title:        Hartanto Ario Widjaya
description:  Student and Mainframer
url:          "https://hartan.to"

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume:
  avatar:             true
  name:               Hartanto Ario Widjaya
  title:              Student and Mainframer
  email:              "96==@o92CE2?]E@"
  intro:              "<p>I'm a student from Singapore who is looking to explore career options in mainframe. Why? Because they are fun to explore. Additionally, I'm one of the Grand Prize Winner for Master the Mainframe 2020! I'm passionate about the constant development of the mainframe, especially in hybrid clouds and application development.</p><p>I'm currently looking for internship opportunities remotely or in-person in Singapore, and I will be looking for full-time employment in Singapore when I conclude my undergraduate studies in the Summer of 2023.</p>"
  looking_for_work:   "yes"

resume_section:
  experience:      true
  education:       true
  projects:        false
  skills:          true
  recognition:     true
  links:           true
  associations:    true
  credentials:     true
  interests:       true
  language:        true

resume_social_links:
  github:            https://github.com/tanto259
  twitter:           https://twitter.com/tanto259
  linkedin:          https://www.linkedin.com/in/hartantoariowidjaya
  website:           https://securitypuppy.com
  facebook:          https://www.facebook.com/tanto259
  instagram:         https://www.instagram.com/tanto259
resume_print_social_links:      true

resume_theme:                   default

author:
  name:     Hartanto Ario Widjaya
  twitter:  tanto259
  picture:  "/images/avatar.jpg"

twitter:
  username: tanto259
  card:     summary

logo: "/images/avatar.jpg"

social:
  name: Hartanto Ario Widjaya
  links:
    - https://twitter.com/tanto259
    - https://www.facebook.com/tanto259
    - https://www.linkedin.com/in/hartantoariowidjaya
    - https://www.instagram.com/tanto259
    - https://github.com/tanto259
    - https://securitypuppy.com

webmaster_verifications:
  google: 8cZJ7K74aI81G83l-AG_7MegZmsRWMNe7rXrVlvrqo8
  yandex: e19915b37a81f438
  bing:   0C8DA626DE53E04C6AF918B5FB85176E

plugins:
  - jekyll-seo-tag

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .well-known