title:        Hartanto Ario Widjaya
description:  Mainframer
url:          "https://hartan.to"

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume:
  avatar:             true
  name:               Hartanto Ario Widjaya
  title:              Mainframer
  intro:              "<p>I'm a system engineer from Singapore who is working with mainframes. Why? Because they are fun to explore :)</p>"
  contact:            "yes"

resume_section:
  experience:      true
  education:       true
  projects:        true
  skills:          true
  recognition:     true
  links:           true
  associations:    true
  credentials:     true
  speaking:        true
  interests:       true
  language:        true

resume_social_links:
  github:            https://github.com/tanto259
  twitter:           https://twitter.com/tanto259
  linkedin:          https://www.linkedin.com/in/hartantoariowidjaya
  website:           https://securitypuppy.com
  facebook:          https://www.facebook.com/tanto259
  instagram:         https://www.instagram.com/tanto259
resume_print_social_links:      true

resume_theme:                   default

author:
  name:     Hartanto Ario Widjaya
  twitter:  tanto259
  picture:  "/images/avatar.jpg"

twitter:
  username: tanto259
  card:     summary

logo: "/images/avatar.jpg"

social:
  name: Hartanto Ario Widjaya
  links:
    - https://twitter.com/tanto259
    - https://www.facebook.com/tanto259
    - https://www.linkedin.com/in/hartantoariowidjaya
    - https://www.instagram.com/tanto259
    - https://github.com/tanto259
    - https://securitypuppy.com

webmaster_verifications:
  google: 8cZJ7K74aI81G83l-AG_7MegZmsRWMNe7rXrVlvrqo8
  yandex: e19915b37a81f438
  bing:   0C8DA626DE53E04C6AF918B5FB85176E

plugins:
  - jekyll-seo-tag

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .well-known